name: permission_handler_android
description: Permission plugin for Flutter. This plugin provides the Android API to request and check permissions.
version: 10.2.0
homepage: https://github.com/baseflow/flutter-permission-handler
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: permission_handler
    platforms:
      android:
        package: com.baseflow.permissionhandler
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface

dev_dependencies:
  lints: ^2.1.0
  plugin_platform_interface: ^2.1.4
