name: permission_handler_apple
description: Permission plugin for Flutter. This plugin provides the iOS API to request and check permissions.
version: 9.0.7
homepage: https://github.com/baseflow/flutter-permission-handler
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: permission_handler
    platforms:
      ios:
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface

dev_dependencies:
  lints: ^2.1.0
  plugin_platform_interface: ^2.1.4
