name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
version: 10.2.5
repository: https://github.com/baseflow/flutter-permission-handler
issue_tracker: https://github.com/Baseflow/flutter-permission-handler/issues

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  permission_handler_android:
    path: ../permission_handler_android
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface

dev_dependencies:
  lints: ^2.0.1
  mockito: ^5.4.0
  plugin_platform_interface: ^2.1.4
